spring.application.name=inmobiliaria

spring.datasource.url=jdbc:oracle:thin:@inmobiliaria_high?TNS_ADMIN=C:/Users/1107473901-35599/Downloads/Wallet_inmobiliaria
spring.datasource.username=ADMIN
spring.datasource.password=Overwatch2026
spring.jpa.hibernate.ddl-auto=validate