spring.application.name=inmobiliaria

# Aqui usamos las variables ${...}

# Using wallet in local filesystem (temporary, for testing)
TNS_ADMIN_WALLET=/Users/javierruiz/Downloads/Wallet_inmobiliaria
spring.datasource.url=jdbc:oracle:thin:@inmobiliaria_high?TNS_ADMIN=${TNS_ADMIN_WALLET}
spring.datasource.username=ADMIN
spring.datasource.password=Overwatch2026

spring.jpa.hibernate.ddl-auto=none






